### ISSUE TITLE
Maximum number of subscriptions

### ISSUE THREAD

**Issue by JonasJurczok** [Inxton/Feedback#13]
Helo,

we have another question regarding updates of values from the PLC to the C# application.

It seems we have two ways to get informed about changes in PLC data.

1. Query the data by one of the three provided methods (synchron, cyclic, batch)
2. Subscribe to changes to an object.

I would prefer option 2 because it is less busy and the application doesn't have to actively refresh state all the time.

Is there a maximum number of subscriptions I can have at any given moment?

Or is there a better best practice?

I've seen the WPF example with the counter, however I don't know enough about WPF internals to understand if the system is silently quering the information or actually listening to updates.

Thanks.
Jonas

**Comment by PTKu** [comment]
There is no limit to the number of subscriptions on the connector (these subscriptions differ from those of ADS API). Of course, with many variables to observe, the performance may degrade (how many variables will start to affect the performance depends on many factors HW, networking, etc.), but in general, you do not have to worry about that; the threshold is pretty high.

What really happens when you subscribe to a variable change is that this variable will be added to the cyclic-read-loop in your application. When the value changes, the delegate is fired, and you can react to that change. 

Just briefly about different accesses to the variables:

# Synchron 
- is really about how we deal with access from the application flow perspective, it simply means access (read or write) and then returning to the program.
- it is the slowest way of accessing variables, not suitable for large data.

# Batch

- batch read or write is the fast way of accessing whole structures.
- similarly to Synchron when calling `Read` or `Write` on a structure the action is perfomed on the PLC and the control is returned to your program.

In both Synchron and Batch, you can be sure that the values were Read/Written once executed.

# Cyclic
- this approach is different. The cyclic value is read/written in a closed optimized loop in the background.
- Cyclic notifies about changes via `INotifyPropertyChanged`, which makes it suitable for UI frameworks (like WPF, Blazor, MAUI) as they can react to the changes over that interface.
- Anytime the application accesses the Cyclic property for reading, the respective variable will be added to the optimized loop for cyclic access.

There is yet another property on built-in types called `LastValue`, which will contain the last read value of any previous methods.

Hope it is helpful

**Comment by JonasJurczok** [comment]
Ahhh okay. I thought the subscriptions are added to the PLC side of thinks, but if you do this via the cyclic updates in the background that is of course a lot better as there is really effectively no limit.

Awesome, thank you :)

Then I just have to read every variable once and then subscribe to the ones I'm interested in. Thanks :)
