### ISSUE TITLE
Is there documentation on inxton dependency management for PLC code/libraries?

### ISSUE THREAD

**Issue by JonasJurczok** [Inxton/Feedback#14]
Hi,

while evaluating Inxton I stumlbed over [this video](https://www.youtube.com/watch?v=tbEAuOBfmMw) where you demonstrate how to install a twincat library including "backend" source code.

This is a really compelling feature for us.

However I could not find anything in the documentation on how to actually set this up.

Is it as easy as packaging a simple connector project with nuget or are there specific steps to take?

It might be obvious for people familiar with the dotnet/C# way of doing things, so it might be that I just lack knowledge/practice here :)

However a short step by step guide in your documentation would work wonders for adoptability.

Best,
Jonas

**Comment by PTKu** [comment]
There is really no documentation for this feature, it was developed for the needs of TcOpen and MTS (inxton's parent company) to handle the dependencies in a consistent way.

Anyways there are few conditions that must be met for the library to be compiled and packed into NuGet package.

First you will need to make sure that the version number of the .NET assembly matches the version number of the plc project. It should follow [semantic versioning](https://semver.org/). The assembly info of your PlcConnector project must include `AssemblyInformationalVersion` attribute:
Where major.minor.patch.build must match the version set of the PLC project.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/61538034/199297542-b60ae7f0-852f-4310-8722-85a8b2942e2a.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/61538034/199298727-fdfc4373-7f82-4a1f-a2cd-dc87365d4ee2.png">

Then in order to pack the files into NuGet package you will need to add files form `_meta` folder of the PlcConnector project.

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/61538034/199299086-7eb41c6e-cdb6-42f1-b4c5-f6d38a575207.png">

With this when you pack the NuGet package you'll get all the inxton compiler needs to add the library to the Plc project.

In the video you mention the inxton builder is run automatically upon build; you may need to run it manually.

Few remarks: for all this to work there was some tweaking needed for the Automation interface, file system etc. So from the perspective of performance there is not really much we could do, but it works. 

Hope it helps.

**Comment by JonasJurczok** [comment]
Hi,
thanks for the reply. I will try this out but maybe we can get around the whole issue with a better project setup. At least for the beginning.

Thanks.
