### ISSUE TITLE
Documentation about automated testing

### ISSUE THREAD

**Issue by JonasJurczok** [Inxton/Feedback#15]
Hello,

is there documentation on how to do automated testing with Inxton?
I've seen in a video that there are apparently different ways to connect to the PLC, including passing in a dummy controller to run locally without an actual PLC.

Is there a comprehensive writeup/video/starter guide on how to do automated testing as part of a CI build?

Best,
Jonas

**Comment by PTKu** [comment]
Hi @JonasJurczok,

This one is hard... 

automated testing is not officially feature of Inxton. We do automated testing in TcOpen using some features of Inxton. Briefly, we use PLC Twin to access the the object in the plc, we run the test either using RpcEnabled (somewhat slow) or specific context object to execute tests:

something like this:

https://github.com/TcOpenGroup/TcOpen/blob/dev/src/TcoPneumatics/src/XaeTcoPneumatics/TcoPneumaticsTests/POUs/CylinderTests/CylinderTestContext.TcPOU


We then use nUnit (xUnit) framework to run and assert. 

here is an example of that:

https://github.com/TcOpenGroup/TcOpen/blob/dev/src/TcoPneumatics/tests/TcoPneumaticsTests_nUnit/CylinderTests.cs


TcOpen repository uses [psake](https://github.com/psake/psake) to run the pipeline [here is the actual script](https://github.com/TcOpenGroup/TcOpen/blob/dev/pipelines/build.ps1).

How ever more recently we use [cake](https://github.com/cake-build/cake) you can find the build project [here](https://github.com/TcOpenGroup/tcopen-app-templates/tree/dev/cake) specifically the build and testing are [here](https://github.com/TcOpenGroup/tcopen-app-templates/blob/dev/cake/templates/mts-s-template/mts_s_template.cs); currently are test disabled 😨, but uncommenting [this](https://github.com/TcOpenGroup/tcopen-app-templates/blob/e4b55f08fe70eb85678a889af6097782ba9f394f/cake/templates/mts-s-template/mts_s_template.cs#L123) will work... 

This is very complex topic it would deserve some video to explain the details.

Regarding CI/CD I have to warn you; it is not easy to maintain, in particular because of the way the codesys is integrated by TwinCAT into Visual Studio. The fact that you need to have an active instance of visual studio running when using the Automation Interface will give you a lot of headache. 


If you want something more compact I would suggest using [TcUnit](https://github.com/tcunit/TcUnit) for unit testing...

**Comment by JonasJurczok** [comment]
Morning :)

yeah, we have TcUnit running and it works well for the PLC part. But if we move to Inxton I would like to test the C# part as well.

Thanks for the many links. I will work through them and try to find a workable path for us.
